# Generated by Django 2.0 on 2018-01-28 09:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query_utils
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('game', '0014_auto_20180128_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.PositiveIntegerField()),
                ('position', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_type', models.ForeignKey(limit_choices_to=django.db.models.query_utils.Q(django.db.models.query_utils.Q(('app_label', 'character'), ('model', 'Player'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'character'), ('model', 'NPC'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'thing'), ('model', 'Item'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'thing'), ('model', 'Knowledge'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'thing'), ('model', 'Rol'), _connector='AND'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='content_of', to='contenttypes.ContentType')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='game.Game')),
            ],
        ),
    ]
