# Generated by Django 2.0 on 2018-01-28 09:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_auto_20170713_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision_distance', models.PositiveIntegerField(default=100)),
                ('meeting_distance', models.PositiveIntegerField(default=20)),
                ('visible_character', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='child_challenges',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='depends',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='auto_assign_clue',
            new_name='is_template',
        ),
        migrations.RemoveField(
            model_name='game',
            name='author',
        ),
        migrations.RemoveField(
            model_name='game',
            name='challenges',
        ),
        migrations.RemoveField(
            model_name='game',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='game',
            name='name',
        ),
        migrations.RemoveField(
            model_name='game',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='game',
            name='visible_players',
        ),
        migrations.AddField(
            model_name='game',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='game',
            name='title',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Challenge',
        ),
        migrations.AddField(
            model_name='game',
            name='preferences',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='game', to='game.Preference'),
            preserve_default=False,
        ),
    ]
